version: "3.7"
services:
  frontend:
    user: "${UID}:${GID}"
    build:
      context: frontend/
      dockerfile: ../docker/frontend.dockerfile
    volumes:
        - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
  backend:
    user: "${UID}:${GID}"
    build:
      context: backend/
      dockerfile: ../docker/backend.dockerfile
    volumes:
      - ./backend/:/backend
    working_dir: /backend
    ports:
      - "8000:8000"
    tty: true
